kind: pipeline
type: docker
name: example
steps:
  - name: build
    image: gradle:jdk8
    commands:
      - gradle clean build
    volumes:
      - name: gradlerep
        path: /root/.gradle
    when:
      branch: dev
      event: [ push ]
  - name: docker
    image: plugins/docker
    settings:
      username: docker
      password: q1OPcR373rEyicXm
      registry: 172.31.30.5:8082
      insecure: true
      repo: 172.31.30.5:8082/example
      auto_tag: false
#      mirror: 172.31.30.5:8082
    when:
      branch: dev
      event: [ push ]