kind: pipeline
type: docker
name: unit
steps:
  - name: build
    image: maven:3.6.2-jdk-8
    commands:
      - mvn assembly:assembly
    volumes:
      - name: mavenrep
        path: /root/.m2
    when:
      branch: master
      event: [ push ]
  - name: docker
    image: plugins/docker
    command:
      -  docker login -u docker -p q1OPcR373rEyicXm 172.31.16.219:8082
    settings:
      username: admin
      password: d66d8da9-72c6-4561-86ee-d391f3d7962b
      registry: 172.31.30.5:8082
      insecure: true
      repo: 172.31.30.5:8082/example
      auto_tag: true
#      mirror: 172.31.30.5:8082
    when:
      branch: master
      event: [ push ]