kind: pipeline
type: docker
name: example
steps:
  - name: build
    image: gradle:jdk8
    commands:
      - gradle clean build
      - echo git rev-parse --short HEAD
      - git rev-parse --short HEAD > .tags
    volumes:
      - name: gradlerep
        path: /root/.gradle
    when:
      branch: dev
      event: [ push ]
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: 172.31.30.5:8082
      insecure: true
      repo: 172.31.30.5:8082/example
      auto_tag: false
#      mirror: 172.31.30.5:8082
    when:
      branch: dev
      event: [ push ]